# Generated by Django 4.2.16 on 2024-11-19 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100, verbose_name='상품코드')),
                ('bank_name', models.CharField(max_length=100, verbose_name='은행명')),
                ('product_name', models.CharField(max_length=200, verbose_name='상품명')),
                ('maturity_term', models.CharField(blank=True, max_length=100, null=True, verbose_name='만기기간')),
                ('type', models.CharField(choices=[('DEPOSIT', '예금'), ('SAVINGS', '적금'), ('ANNUITY_SAVINGS', '연금저축'), ('MORTGAGE_LOAN', '주택담보대출'), ('CREDIT_LOAN', '신용대출'), ('RENT_HOUSE_LOAN', '전세자금대출')], max_length=20, verbose_name='상품종류')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='찜한 날짜')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '찜 목록',
                'verbose_name_plural': '찜 목록',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'product_code')},
            },
        ),
    ]
