# Generated by Django 4.2.16 on 2024-11-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_rename_product_code_wishlist_fin_prdt_cd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='mtrt_int',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='만기기간'),
        ),
    ]
