# Generated by Django 4.2.16 on 2024-11-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='annual_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='연간 급여(원)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='asset',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='총 자산(원)', max_digits=15, null=True),
        ),
    ]
