# Generated by Django 4.2.16 on 2024-11-18 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_code', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('DEPOSIT', '예금'), ('SAVINGS', '적금'), ('ANNUITY_SAVINGS', '연금저축'), ('MORTGAGE_LOAN', '주택담보대출'), ('CREDIT_LOAN', '신용대출'), ('RENT_HOUSE_LOAN', '전세자금대출')], default='DEPOSIT', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
